---
- name: Configure PingFederate 12.3 with MySQL backend
  hosts: pingfederate_nodes
  become: yes
  vars:
    mysql_host: "db.example.com"
    mysql_port: 3306
    mysql_db: "pingfederate_db"
    mysql_user: "pf_user"
    mysql_password: "StrongPassword!"
    mysql_root_user: "root"
    mysql_root_password: "RootPassword!"
    mysql_connector_version: "8.0.30"
    pf_home: "/opt/pingfederate-12.3"

  tasks:
    - name: Ensure MySQL DB exists
      community.mysql.mysql_db:
        login_host: "{{ mysql_host }}"
        login_user: "{{ mysql_root_user }}"
        login_password: "{{ mysql_root_password }}"
        name: "{{ mysql_db }}"
        state: present
        encoding: utf8mb4
        collation: utf8mb4_unicode_ci

    - name: Ensure MySQL user exists
      community.mysql.mysql_user:
        login_host: "{{ mysql_host }}"
        login_user: "{{ mysql_root_user }}"
        login_password: "{{ mysql_root_password }}"
        name: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
        priv: "{{ mysql_db }}.*:ALL"
        host: "%"
        state: present

    - name: Download MySQL JDBC driver
      get_url:
        url: "https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-j-{{ mysql_connector_version }}.tar.gz"
        dest: "/tmp/mysql-connector.tar.gz"

    - name: Extract JDBC driver
      unarchive:
        src: "/tmp/mysql-connector.tar.gz"
        dest: "/tmp/"
        remote_src: yes

    - name: Copy JDBC jar to PingFederate lib
      copy:
        src: "/tmp/mysql-connector-j-{{ mysql_connector_version }}/mysql-connector-j-{{ mysql_connector_version }}.jar"
        dest: "{{ pf_home }}/server/default/lib/"
        mode: '0644'

    - name: Create JDBC datastore config
      copy:
        dest: "{{ pf_home }}/server/default/data/config-store/data-store-mysql.xml"
        content: |
          <map>
            <entry key="id" value="mysql-ds"/>
            <entry key="name" value="MySQL Datastore"/>
            <entry key="driver" value="com.mysql.cj.jdbc.Driver"/>
            <entry key="url" value="jdbc:mysql://{{ mysql_host }}:{{ mysql_port }}/{{ mysql_db }}?useSSL=false&amp;serverTimezone=UTC"/>
            <entry key="user" value="{{ mysql_user }}"/>
            <entry key="password" value="{{ mysql_password }}"/>
            <entry key="validationQuery" value="SELECT 1"/>
          </map>

    - name: Configure Cluster State Service to use MySQL
      copy:
        dest: "{{ pf_home }}/server/default/data/config-store/cluster-state-service.xml"
        content: |
          <map>
            <entry key="dataStore" value="mysql-ds"/>
          </map>

    - name: Configure OAuth Persistent Grants to use MySQL
      copy:
        dest: "{{ pf_home }}/server/default/data/config-store/org.sourceid.oauth20.domain.PersistentGrantManagerJdbcImpl.xml"
        content: |
          <map>
            <entry key="dataStore" value="mysql-ds"/>
          </map>

    - name: Import PingFederate schema into MySQL
      community.mysql.mysql_db:
        login_host: "{{ mysql_host }}"
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        name: "{{ mysql_db }}"
        state: import
        target: "{{ pf_home }}/server/default/conf/database/mysql/schema-mysql.sql"

    - name: Restart PingFederate
      systemd:
        name: pingfederate
        state: restarted
        enabled: yes
