name: Build And Deploy Workstream

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Echo Hello
      run: echo "hello"

  wiz:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Echo Hello
      run: echo "hello"

  build_efs:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Echo Hello
      run: echo "hello"      

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Echo Hello
      run: echo "hello"      

  deploy_efs:
    runs-on: ubuntu-latest
    needs: build_efs

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Echo Hello
      run: echo "hello"  