name: Check Workstream

on: [push]

jobs:
  check-esp-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Echo Hello
      run: echo "hello"

  check-last-import-log:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Echo Hello
      run: echo "hello"      

  check-content-:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Echo Hello
      run: echo "hello"      